/**
 * 发布今天的计划内容到 auto-generated-guides.json
 * 
 * 运行: npx tsx scripts/publish-today.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface Guide {
  id: string;
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  excerpt: string;
  category: string;
  publishDate: string;
  updateDate: string;
  author: string;
  keywords: string[];
  searchVolume?: string;
  sections: { heading: string; content: string }[];
  relatedDlls: string[];
}

function main() {
  console.log('📅 Publishing today\'s scheduled content...\n');
  
  const today = new Date().toISOString().split('T')[0];
  console.log(`Today: ${today}\n`);
  
  // 读取计划内容
  const scheduledPath = path.join(__dirname, '../src/data/scheduled-guides.json');
  const scheduledContent = JSON.parse(fs.readFileSync(scheduledPath, 'utf-8'));
  
  const guides: Guide[] = scheduledContent.guides || [];
  console.log(`📊 Total scheduled guides: ${guides.length}`);
  
  // 找出今天要发布的内容
  const todaysGuides = guides.filter(g => g.publishDate === today);
  console.log(`📝 Guides to publish today: ${todaysGuides.length}`);
  
  if (todaysGuides.length === 0) {
    console.log('\n❌ No guides scheduled for today.');
    console.log('Check scheduled-guides.json for available dates.');
    return;
  }
  
  // 显示今天的内容
  console.log('\nToday\'s content:');
  todaysGuides.forEach((g, i) => {
    console.log(`  ${i + 1}. ${g.slug}`);
    console.log(`     Title: ${g.title}`);
    console.log(`     Category: ${g.category}`);
  });
  
  // 读取现有的已发布内容
  const autoGeneratedPath = path.join(__dirname, '../src/data/auto-generated-guides.json');
  let existingGuides: Guide[] = [];
  
  if (fs.existsSync(autoGeneratedPath)) {
    try {
      existingGuides = JSON.parse(fs.readFileSync(autoGeneratedPath, 'utf-8'));
      if (!Array.isArray(existingGuides)) {
        existingGuides = [];
      }
    } catch (e) {
      console.log('Creating new auto-generated-guides.json');
    }
  }
  
  console.log(`\n📚 Existing published guides: ${existingGuides.length}`);
  
  // 合并新内容 (避免重复)
  const existingSlugs = new Set(existingGuides.map(g => g.slug));
  const newGuides = todaysGuides.filter(g => !existingSlugs.has(g.slug));
  
  if (newGuides.length === 0) {
    console.log('\n⚠️ All of today\'s guides are already published!');
    return;
  }
  
  const allGuides = [...existingGuides, ...newGuides];
  
  // 保存
  fs.writeFileSync(autoGeneratedPath, JSON.stringify(allGuides, null, 2));
  
  console.log(`\n✅ Published ${newGuides.length} new guides!`);
  console.log(`📊 Total published guides: ${allGuides.length}`);
  
  // 更新 scheduled-guides.json，标记已发布的内容
  const remainingGuides = guides.filter(g => g.publishDate !== today || !newGuides.find(ng => ng.slug === g.slug));
  
  const updatedScheduled = {
    ...scheduledContent,
    lastPublishDate: today,
    publishedToday: newGuides.length,
    guides: remainingGuides
  };
  
  fs.writeFileSync(scheduledPath, JSON.stringify(updatedScheduled, null, 2));
  console.log(`📅 Remaining scheduled guides: ${remainingGuides.length}`);
  
  console.log('\n🎉 Done! Next steps:');
  console.log('1. git add -A');
  console.log('2. git commit -m "Publish daily content"');
  console.log('3. git push');
}

main();
