// SEO 长尾词指南/博客数据库
// 用于捕获 0xc000007b, Event ID 1000 等高价值搜索流量

// 导入自动生成的指南
import autoGeneratedGuides from './auto-generated-guides.json';
// 导入定时发布的指南 (包含12月7日及之后的游戏修复文章)
import scheduledGuidesData from './scheduled-guides.json';

export interface GuideSection {
  heading: string;
  content: string;
}

export interface Guide {
  id: string;
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  excerpt: string;
  category: 'Error Codes' | 'Installation' | 'Gaming' | 'System' | 'Event Logs';
  publishDate: string;
  updateDate: string;
  author: string;
  sections: GuideSection[];
  relatedDlls: string[];
  keywords: string[];
}

export const guidesDatabase: Guide[] = [
  {
    id: 'fix-0xc000007b',
    slug: 'how-to-fix-0xc000007b-error',
    title: 'How to Fix "The application was unable to start correctly (0xc000007b)" Error',
    metaTitle: 'Fix 0xc000007b Error in Windows 11/10 (2025 Guide) | FixMissingDLL',
    metaDescription: 'Complete guide to fix the 0xc000007b application error in Windows 11 and Windows 10. Solutions for GTA V, Elden Ring, Adobe, and other applications.',
    excerpt: 'The 0xc000007b error typically indicates a 32-bit/64-bit DLL mismatch. This guide shows you exactly how to fix it.',
    category: 'Error Codes',
    publishDate: '2025-01-15',
    updateDate: new Date().toISOString().split('T')[0],
    author: 'System Admin Team',
    sections: [
      {
        heading: 'What Causes the 0xc000007b Error?',
        content: `The error code 0xc000007b appears when Windows cannot properly initialize an application. The most common causes are:

**1. Architecture Mismatch**: A 64-bit application is trying to load a 32-bit DLL (or vice versa). This often happens when you manually download DLL files and place them in the wrong folder.

**2. Corrupted Visual C++ Runtime**: The Microsoft Visual C++ Redistributable packages are damaged or incomplete.

**3. Corrupted DirectX Files**: Missing or corrupted DirectX runtime components.

**4. .NET Framework Issues**: Damaged .NET Framework installation.

**5. Corrupted System Files**: Windows system files have become corrupted.`
      },
      {
        heading: 'Solution 1: Reinstall Visual C++ Redistributables (Most Effective)',
        content: `This is the most effective solution for 90% of 0xc000007b errors.

**Step 1**: Press \`Win + R\`, type \`appwiz.cpl\`, press Enter.

**Step 2**: Uninstall ALL "Microsoft Visual C++ Redistributable" entries (there may be several).

**Step 3**: Download the All-in-One Visual C++ Redistributable installer:
- [Official Microsoft VC++ 2015-2022 (x64)](https://aka.ms/vs/17/release/vc_redist.x64.exe)
- [Official Microsoft VC++ 2015-2022 (x86)](https://aka.ms/vs/17/release/vc_redist.x86.exe)

**Step 4**: Install BOTH x64 and x86 versions (even on 64-bit Windows).

**Step 5**: Restart your computer.`
      },
      {
        heading: 'Solution 2: Reinstall DirectX End-User Runtime',
        content: `Many games require legacy DirectX 9.0c components that aren't included with Windows 10/11.

**Step 1**: Download the [DirectX End-User Runtime Web Installer](https://www.microsoft.com/en-us/download/details.aspx?id=35).

**Step 2**: Run the installer and follow the prompts.

**Step 3**: Restart your computer.

**Note**: This does NOT replace DirectX 12 - it installs legacy DirectX 9/10/11 components alongside it.`
      },
      {
        heading: 'Solution 3: Run System File Checker',
        content: `Corrupted Windows system files can cause 0xc000007b errors.

**Step 1**: Open Command Prompt as Administrator (search "cmd", right-click, "Run as administrator").

**Step 2**: Run the following commands:

\`\`\`
sfc /scannow
\`\`\`

Wait for the scan to complete (10-15 minutes).

**Step 3**: If issues are found, run DISM:

\`\`\`
DISM /Online /Cleanup-Image /RestoreHealth
\`\`\`

**Step 4**: Restart your computer.`
      },
      {
        heading: 'Solution 4: Check for 32-bit/64-bit Confusion',
        content: `If you've manually downloaded DLL files, you may have placed them in the wrong folder.

**For 64-bit applications**:
- DLLs should be in: \`C:\\Windows\\System32\`

**For 32-bit applications on 64-bit Windows**:
- DLLs should be in: \`C:\\Windows\\SysWOW64\`

Yes, this is confusing! The folder names are backwards for legacy compatibility reasons.

**Tip**: Delete any manually downloaded DLL files and use the official runtime installers instead.`
      },
      {
        heading: 'Solution 5: Reinstall .NET Framework',
        content: `For applications that use .NET:

**Step 1**: Open Windows Settings > Apps > Optional Features.

**Step 2**: Look for ".NET Framework 3.5" and ".NET Framework 4.8" - ensure both are installed.

**Step 3**: If issues persist, download the [.NET Framework Repair Tool](https://www.microsoft.com/en-us/download/details.aspx?id=30135).`
      }
    ],
    relatedDlls: ['vcruntime140.dll', 'msvcp140.dll', 'd3dx9_43.dll', 'xinput1_3.dll'],
    keywords: ['0xc000007b', '0xc000007b fix', 'application unable to start', 'windows 11 0xc000007b', 'gta v 0xc000007b', 'elden ring 0xc000007b']
  },
  {
    id: 'install-directx',
    slug: 'install-directx-windows-11',
    title: 'How to Install DirectX 12, 11, and 9 on Windows 11/10 (Complete Guide)',
    metaTitle: 'Install DirectX 12/11/9 on Windows 11/10 (2025) | Fix d3dx9_43.dll Missing',
    metaDescription: 'Step-by-step guide to install or reinstall DirectX on Windows 11 and Windows 10. Fix missing d3dx9_43.dll, d3dx9_42.dll, and other DirectX errors.',
    excerpt: 'Windows 11 comes with DirectX 12, but many games need legacy DirectX 9/10/11 files. Here\'s how to install them all.',
    category: 'Installation',
    publishDate: '2025-01-10',
    updateDate: new Date().toISOString().split('T')[0],
    author: 'Gaming Support Team',
    sections: [
      {
        heading: 'Understanding DirectX Versions',
        content: `**DirectX 12**: Pre-installed on Windows 10/11. Cannot be separately downloaded.

**DirectX 11/10**: Also pre-installed, but some components may be missing.

**DirectX 9.0c**: Legacy version required by many older games. NOT included with Windows 10/11 by default.

When you see errors like "d3dx9_43.dll is missing", you need to install the **DirectX End-User Runtime**, which provides the legacy DirectX 9/10/11 support libraries.`
      },
      {
        heading: 'Method 1: Install DirectX End-User Runtime (Recommended)',
        content: `This installs all legacy DirectX components (d3dx9_xx.dll, xinput1_x.dll, xaudio2_x.dll, etc.).

**Step 1**: Download the [DirectX End-User Runtime Web Installer](https://www.microsoft.com/en-us/download/details.aspx?id=35) from Microsoft.

**Step 2**: Run \`dxwebsetup.exe\`.

**Step 3**: Follow the installation wizard.

**Step 4**: Restart your computer.

This will install approximately 100 MB of DirectX runtime files.`
      },
      {
        heading: 'Method 2: Offline Installation',
        content: `If you have multiple computers or a slow internet connection:

**Step 1**: Download the [DirectX End-User Runtimes (June 2010)](https://www.microsoft.com/en-us/download/details.aspx?id=8109) - this is a 96 MB standalone package.

**Step 2**: Extract the files to a folder.

**Step 3**: Run \`DXSETUP.exe\` from the extracted folder.

This package contains all DirectX 9/10/11 runtime components released through June 2010.`
      },
      {
        heading: 'Method 3: Check DirectX Version',
        content: `To verify your DirectX installation:

**Step 1**: Press \`Win + R\`.

**Step 2**: Type \`dxdiag\` and press Enter.

**Step 3**: The DirectX Diagnostic Tool will show your DirectX version.

On the "Display" tab, you can see the Feature Level your GPU supports.`
      },
      {
        heading: 'Troubleshooting: DirectX Still Not Working',
        content: `If games still report DirectX errors after installation:

**1. Run as Administrator**: Right-click the game executable, select "Run as administrator".

**2. Install to Game Folder**: Some games include their own DirectX installer in the game folder (usually in a "redist" or "_CommonRedist" subfolder). Run it.

**3. Update GPU Drivers**: Outdated graphics drivers can cause DirectX issues.
   - NVIDIA: [nvidia.com/drivers](https://www.nvidia.com/drivers)
   - AMD: [amd.com/support](https://www.amd.com/support)
   - Intel: [intel.com/support](https://www.intel.com/support)

**4. Verify Game Files**: On Steam, right-click the game > Properties > Local Files > Verify integrity.`
      }
    ],
    relatedDlls: ['d3dx9_43.dll', 'd3dx9_42.dll', 'd3dx9_41.dll', 'xinput1_3.dll', 'xinput1_4.dll', 'xaudio2_7.dll', 'd3dcompiler_47.dll'],
    keywords: ['install directx', 'directx 12 download', 'directx 9 windows 11', 'd3dx9_43.dll missing', 'directx end user runtime']
  },
  {
    id: 'visual-cpp-guide',
    slug: 'install-visual-cpp-redistributable-all-versions',
    title: 'Install All Visual C++ Redistributable Versions (2005-2022)',
    metaTitle: 'Download All Visual C++ Redistributables (2005-2022) | Complete Guide',
    metaDescription: 'Complete guide to install all Microsoft Visual C++ Redistributable packages from 2005 to 2022. Fix vcruntime140.dll, msvcp140.dll, and msvcr errors.',
    excerpt: 'Many Windows applications require Visual C++ Runtime. Here\'s how to install all versions and fix missing DLL errors.',
    category: 'Installation',
    publishDate: '2025-01-08',
    updateDate: new Date().toISOString().split('T')[0],
    author: 'System Admin Team',
    sections: [
      {
        heading: 'What is Visual C++ Redistributable?',
        content: `The Visual C++ Redistributable is a runtime library required by programs built with Microsoft Visual Studio.

Each version of Visual Studio (2005, 2008, 2010, 2012, 2013, 2015, 2017, 2019, 2022) has its own runtime, and programs require the specific version they were compiled with.

**Good news**: Visual C++ 2015, 2017, 2019, and 2022 share the same runtime package. Installing the latest (2022) version covers all of them.`
      },
      {
        heading: 'Download Links (Official Microsoft)',
        content: `**Visual C++ 2015-2022 (Covers 2015, 2017, 2019, 2022)**:
- [x64 (64-bit)](https://aka.ms/vs/17/release/vc_redist.x64.exe)
- [x86 (32-bit)](https://aka.ms/vs/17/release/vc_redist.x86.exe)
- [ARM64](https://aka.ms/vs/17/release/vc_redist.arm64.exe)

**Visual C++ 2013**:
- [x64](https://aka.ms/highdpimfc2013x64enu)
- [x86](https://aka.ms/highdpimfc2013x86enu)

**Visual C++ 2012**:
- [x64](https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe)
- [x86](https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x86.exe)

**Visual C++ 2010**:
- [x64](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x64.exe)
- [x86](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe)

**Visual C++ 2008**:
- [x64](https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x64.exe)
- [x86](https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x86.exe)

**Visual C++ 2005**:
- [x64](https://download.microsoft.com/download/8/B/4/8B42259F-5D70-43F4-AC2E-4B208FD8D66A/vcredist_x64.exe)
- [x86](https://download.microsoft.com/download/8/B/4/8B42259F-5D70-43F4-AC2E-4B208FD8D66A/vcredist_x86.exe)`
      },
      {
        heading: 'Installation Instructions',
        content: `**Important**: On 64-bit Windows, install BOTH x64 and x86 versions of each package. Many 32-bit programs still require the x86 runtime.

**Step 1**: Download all the packages you need.

**Step 2**: Install them in order from oldest to newest (2005 → 2022).

**Step 3**: Restart your computer after all installations.

**Pro Tip**: You can use the "VisualCppRedist AIO" installer from TechPowerUp which bundles all versions in a single installer.`
      },
      {
        heading: 'Repair Existing Installation',
        content: `If you already have Visual C++ installed but it's corrupted:

**Step 1**: Open Control Panel > Programs > Programs and Features.

**Step 2**: Find "Microsoft Visual C++ 20XX Redistributable".

**Step 3**: Right-click > Change > Repair.

Alternatively, uninstall all Visual C++ packages and reinstall them fresh.`
      },
      {
        heading: 'Which DLLs Does Each Version Provide?',
        content: `**2015-2022** (vcruntime140.dll, msvcp140.dll, vcruntime140_1.dll, concrt140.dll, vcomp140.dll)

**2013** (msvcr120.dll, msvcp120.dll)

**2012** (msvcr110.dll, msvcp110.dll)

**2010** (msvcr100.dll, msvcp100.dll)

**2008** (msvcr90.dll, msvcp90.dll)

**2005** (msvcr80.dll, msvcp80.dll)`
      }
    ],
    relatedDlls: ['vcruntime140.dll', 'vcruntime140_1.dll', 'msvcp140.dll', 'msvcp140_1.dll', 'concrt140.dll', 'vcomp140.dll', 'mfc140u.dll'],
    keywords: ['visual c++ redistributable', 'vcruntime140.dll download', 'msvcp140.dll missing', 'microsoft visual c++ 2015', 'all in one visual c++']
  },
  {
    id: 'event-id-1000',
    slug: 'fix-event-id-1000-application-error',
    title: 'Fix Event ID 1000 Application Error in Windows Event Viewer',
    metaTitle: 'Fix Event ID 1000 Application Error (2025) | Windows Event Viewer Guide',
    metaDescription: 'Complete guide to diagnose and fix Event ID 1000 Application Error in Windows Event Viewer. Troubleshoot ntdll.dll, kernelbase.dll, and other faulting module errors.',
    excerpt: 'Event ID 1000 indicates an application crash. Learn how to read the error details and fix the underlying cause.',
    category: 'Event Logs',
    publishDate: '2025-01-20',
    updateDate: new Date().toISOString().split('T')[0],
    author: 'Windows Support Team',
    sections: [
      {
        heading: 'Understanding Event ID 1000',
        content: `Event ID 1000 is logged in Windows Event Viewer when an application crashes due to an unhandled exception.

**To view the error**:
1. Press \`Win + R\`, type \`eventvwr.msc\`, press Enter.
2. Navigate to: Windows Logs > Application.
3. Look for entries with Source: "Application Error" and Event ID: 1000.

The error contains these key fields:
- **Faulting application name**: The program that crashed.
- **Faulting module name**: The DLL that caused the crash (e.g., ntdll.dll, vcruntime140.dll).
- **Exception code**: The type of error (e.g., 0xc0000005 = Access Violation).`
      },
      {
        heading: 'Common Faulting Modules and Fixes',
        content: `**ntdll.dll** - Core Windows system file. Usually indicates:
- Corrupted system files → Run \`sfc /scannow\`
- Incompatible software → Update or uninstall recently installed apps
- Memory issues → Run Windows Memory Diagnostic

**kernelbase.dll** - Windows kernel library:
- Often caused by .NET issues → Repair .NET Framework
- Third-party DLL conflicts → Boot in Safe Mode to test

**vcruntime140.dll / msvcp140.dll** - Visual C++ Runtime:
- Reinstall Visual C++ Redistributable 2015-2022

**ucrtbase.dll** - Universal C Runtime:
- Install latest Windows Updates
- Reinstall Visual C++ Redistributable

**d3d11.dll / d3dx9_43.dll** - DirectX:
- Reinstall DirectX End-User Runtime`
      },
      {
        heading: 'Step-by-Step Troubleshooting',
        content: `**Step 1**: Identify the faulting module from Event Viewer.

**Step 2**: Search for the DLL name on this site to find the appropriate fix.

**Step 3**: If the faulting module is part of the application itself (not a Windows DLL), try:
- Reinstalling the application
- Updating the application to the latest version
- Running the application as Administrator
- Checking for application-specific fixes on the developer's support site

**Step 4**: If crashes persist, collect a crash dump:
\`\`\`
reg add "HKLM\\SOFTWARE\\Microsoft\\Windows\\Windows Error Reporting\\LocalDumps" /v DumpFolder /t REG_EXPAND_SZ /d "C:\\CrashDumps" /f
\`\`\`
Then analyze the dump with WinDbg.`
      },
      {
        heading: 'Common Exception Codes',
        content: `**0xc0000005** - Access Violation
The application tried to read/write protected memory. Often caused by corrupted DLLs or incompatible drivers.

**0xc000007b** - Bad Image Format
32-bit/64-bit mismatch. See our 0xc000007b guide.

**0xc0000142** - DLL Initialization Failed
A DLL failed to initialize. Usually a runtime library issue.

**0xc0000409** - Stack Buffer Overrun
Security check detected buffer overflow. Update the application.

**0x80000003** - Breakpoint
Debug breakpoint hit. May indicate corrupted executable.`
      }
    ],
    relatedDlls: ['ntdll.dll', 'kernel32.dll', 'vcruntime140.dll', 'msvcp140.dll', 'ucrtbase.dll'],
    keywords: ['event id 1000', 'application error', 'faulting module ntdll.dll', 'windows event viewer', 'kernelbase.dll crash']
  },
  {
    id: 'dll-safety',
    slug: 'are-dll-download-sites-safe',
    title: 'Are DLL Download Sites Safe? How to Verify DLL Files',
    metaTitle: 'Are DLL Downloads Safe? How to Verify DLL Files (Security Guide)',
    metaDescription: 'Learn how to verify DLL files are safe using digital signatures, MD5/SHA256 hashes, and VirusTotal. Protect yourself from malware-infected DLLs.',
    excerpt: 'Downloading DLLs from random websites is risky. Learn how to verify files are legitimate and safe.',
    category: 'System',
    publishDate: '2025-01-05',
    updateDate: new Date().toISOString().split('T')[0],
    author: 'Security Team',
    sections: [
      {
        heading: 'The Danger of Random DLL Downloads',
        content: `Many websites offer "free DLL downloads" but these can be:

**1. Malware**: The DLL is actually a virus, trojan, or ransomware.

**2. Outdated**: Old versions that may not fix your problem.

**3. Wrong Architecture**: 32-bit DLL for a 64-bit application.

**4. Wrong Version**: DLL from a different software version.

**The safest approach**: Install the official runtime package (Visual C++, DirectX, .NET) rather than downloading individual DLLs.`
      },
      {
        heading: 'How to Check Digital Signatures',
        content: `Legitimate Microsoft DLLs have digital signatures.

**Step 1**: Right-click the DLL file > Properties.

**Step 2**: Click the "Digital Signatures" tab.

**Step 3**: Select the signature and click "Details".

**Step 4**: Verify the signer is "Microsoft Corporation" or the expected software vendor.

**Warning**: If there's no Digital Signatures tab, the file is NOT signed and may be unsafe.`
      },
      {
        heading: 'Verify with Hash Values',
        content: `Compare the file's hash against known-good values.

**Using PowerShell**:
\`\`\`powershell
Get-FileHash -Path "C:\\path\\to\\file.dll" -Algorithm SHA256
\`\`\`

**Using Command Prompt**:
\`\`\`cmd
certutil -hashfile "C:\\path\\to\\file.dll" SHA256
\`\`\`

Compare the output against the hash values provided on trusted sites (like this one) or Microsoft's documentation.`
      },
      {
        heading: 'Scan with VirusTotal',
        content: `Before using any downloaded DLL:

**Step 1**: Go to [VirusTotal.com](https://www.virustotal.com/).

**Step 2**: Upload the DLL file (or paste its URL).

**Step 3**: Review the scan results from 70+ antivirus engines.

**What to look for**:
- 0 detections = likely safe
- 1-2 detections = possibly false positive, investigate further
- 3+ detections = likely malicious, do not use`
      },
      {
        heading: 'Best Practices for DLL Management',
        content: `**DO**:
✓ Install official runtime packages (Visual C++, DirectX, .NET)
✓ Keep Windows updated
✓ Verify digital signatures before using DLLs
✓ Scan downloaded files with VirusTotal
✓ Create a System Restore point before modifying system files

**DON'T**:
✗ Download DLLs from random "free DLL" sites
✗ Run executables that claim to "fix all DLL errors"
✗ Disable antivirus to run a suspicious DLL
✗ Copy DLLs from one computer to another
✗ Trust DLLs sent via email or messaging apps`
      }
    ],
    relatedDlls: ['vcruntime140.dll', 'msvcp140.dll', 'kernel32.dll', 'ntdll.dll'],
    keywords: ['dll download safe', 'verify dll file', 'dll virus', 'digital signature dll', 'virustotal dll']
  },
  {
    id: 'steam-api-errors',
    slug: 'fix-steam-api64-dll-missing',
    title: 'Fix steam_api64.dll and steam_api.dll Missing Errors',
    metaTitle: 'Fix steam_api64.dll Missing (2025) | Steam API DLL Error Solutions',
    metaDescription: 'Complete guide to fix steam_api64.dll and steam_api.dll missing errors in Steam games. Safe solutions that don\'t involve downloading DLLs.',
    excerpt: 'Steam API DLL errors are common in pirated games, but can also occur in legitimate copies. Here\'s how to fix them properly.',
    category: 'Gaming',
    publishDate: '2025-01-18',
    updateDate: new Date().toISOString().split('T')[0],
    author: 'Gaming Support Team',
    sections: [
      {
        heading: 'Why This Error Occurs',
        content: `The steam_api64.dll (64-bit) and steam_api.dll (32-bit) files are Steam's integration libraries.

**Common causes**:
1. **Pirated games**: Cracks often replace or remove Steam DLLs, which antiviruses quarantine.
2. **Antivirus quarantine**: Even legitimate DLLs get flagged as "HackTool".
3. **Corrupted game files**: Steam download was interrupted or corrupted.
4. **Missing Steam client**: Game requires Steam running in background.`
      },
      {
        heading: 'Solution 1: Verify Game Files (For Legitimate Steam Games)',
        content: `**Step 1**: Open Steam.

**Step 2**: Go to Library > Right-click the game > Properties.

**Step 3**: Click "Local Files" > "Verify integrity of game files".

**Step 4**: Wait for verification (may take several minutes).

Steam will re-download any missing or corrupted files, including steam_api.dll.`
      },
      {
        heading: 'Solution 2: Add Antivirus Exception',
        content: `Many antiviruses (especially Windows Defender) flag steam_api.dll as a "HackTool".

**For Windows Defender**:
1. Open Windows Security > Virus & threat protection.
2. Click "Protection history".
3. Find the quarantined steam_api.dll, click "Restore".
4. Add the game folder to exclusions: Virus & threat protection settings > Manage exclusions > Add an exclusion.

**For other antiviruses**: Check your quarantine/vault and restore the file, then whitelist the game folder.`
      },
      {
        heading: 'Solution 3: Reinstall Steam',
        content: `If multiple games have Steam API errors:

**Step 1**: Uninstall Steam via Control Panel (your games will be preserved).

**Step 2**: Download fresh Steam installer from [store.steampowered.com](https://store.steampowered.com/about/).

**Step 3**: Install Steam to the same location.

**Step 4**: Your games should be detected automatically.`
      },
      {
        heading: 'For Non-Steam Games',
        content: `Some games sold on other platforms (GOG, Epic) may include Steam API for achievements or multiplayer.

**Options**:
1. Check if the game has a non-Steam version (DRM-free from GOG).
2. Copy steam_api.dll from another game that works.
3. Install the Steam client even if you don't own the game there.

**Warning**: Do NOT download steam_api.dll from random websites - it's a prime target for malware injection.`
      }
    ],
    relatedDlls: ['steam_api64.dll', 'steam_api.dll'],
    keywords: ['steam_api64.dll missing', 'steam_api.dll not found', 'steam dll error', 'verify game files steam']
  },
  {
    id: 'fix-ucrtbase-dll',
    slug: 'fix-ucrtbase-dll-missing',
    title: 'How to Fix UCRTBASE.dll Missing Error',
    metaTitle: 'Fix UCRTBASE.dll Missing Error (2025) | Universal CRT Guide',
    metaDescription: 'Complete guide to fix UCRTBASE.dll is missing error. Install Universal C Runtime for Windows to resolve this error.',
    excerpt: 'UCRTBASE.dll is the Universal C Runtime. Learn how to fix this common Windows error.',
    category: 'Error Codes',
    publishDate: '2025-02-07',
    updateDate: new Date().toISOString().split('T')[0],
    author: 'System Admin Team',
    sections: [
      {
        heading: 'What is UCRTBASE.dll?',
        content: `UCRTBASE.dll is the Universal C Runtime (UCRT) base library, a core Windows component.

**Purpose:**
- Provides standard C library functions
- Used by programs compiled with Visual Studio 2015 and later
- Part of Windows 10/11

**On Windows 10/11:**
UCRTBASE.dll is a system file included with Windows.

**On Windows 7/8.1:**
UCRTBASE.dll was provided via Windows Update (KB2999226) or the Visual C++ Redistributable.`
      },
      {
        heading: 'Solution 1: Install Visual C++ Redistributable',
        content: `The UCRT is included with Visual C++ 2015-2022:

**Download Links:**
- [Visual C++ 2015-2022 x64](https://aka.ms/vs/17/release/vc_redist.x64.exe)
- [Visual C++ 2015-2022 x86](https://aka.ms/vs/17/release/vc_redist.x86.exe)

**Steps:**
1. Download both x64 and x86 versions
2. Run x64 installer first
3. Run x86 installer
4. Restart your computer

This should install or repair UCRTBASE.dll.`
      },
      {
        heading: 'Solution 2: Run Windows Update (Windows 7/8.1)',
        content: `On older Windows versions, UCRT is provided via Windows Update:

**Step 1:** Open Windows Update

**Step 2:** Check for updates

**Step 3:** Install all available updates, especially KB2999226 (Universal C Runtime)

**Manual Download:**
If Windows Update doesn't work, download KB2999226 directly:
1. Go to Microsoft Update Catalog (catalog.update.microsoft.com)
2. Search for KB2999226
3. Download the version for your Windows

**Prerequisites:**
KB2999226 requires KB2919355 (Windows 8.1 Update) on Windows 8.1.`
      },
      {
        heading: 'Solution 3: SFC and DISM (Windows 10/11)',
        content: `On Windows 10/11, UCRTBASE.dll is a protected system file:

**Step 1:** Open Command Prompt as Administrator

**Step 2:** Run SFC:
\`\`\`
sfc /scannow
\`\`\`

**Step 3:** If SFC finds issues, run DISM:
\`\`\`
DISM /Online /Cleanup-Image /RestoreHealth
\`\`\`

**Step 4:** Run SFC again:
\`\`\`
sfc /scannow
\`\`\`

**Step 5:** Restart your computer

This will restore the correct UCRTBASE.dll from the Windows component store.`
      }
    ],
    relatedDlls: ['ucrtbase.dll', 'api-ms-win-crt-runtime-l1-1-0.dll'],
    keywords: ['ucrtbase.dll missing', 'universal c runtime', 'ucrt error', 'ucrtbase download']
  },
  {
    id: 'fix-gta-v-dll-errors',
    slug: 'gta-v-dll-errors-fix',
    title: 'How to Fix All DLL Errors in GTA V (Grand Theft Auto 5)',
    metaTitle: 'Fix GTA V DLL Errors - VCRUNTIME140, MSVCP140, D3D Errors (2025)',
    metaDescription: 'Complete guide to fix all DLL errors in GTA V including VCRUNTIME140.dll, MSVCP140.dll, D3DCompiler_47.dll, and 0xc000007b. Get back to Los Santos!',
    excerpt: 'GTA V won\'t start due to missing DLL errors? This comprehensive guide covers all common DLL issues and how to fix them.',
    category: 'Gaming',
    publishDate: '2025-03-01',
    updateDate: new Date().toISOString().split('T')[0],
    author: 'Gaming Support Team',
    sections: [
      {
        heading: 'Common GTA V DLL Errors',
        content: `GTA V players frequently encounter these DLL errors:

**Visual C++ Runtime Errors:**
- VCRUNTIME140.dll is missing
- MSVCP140.dll is missing
- VCRUNTIME140_1.dll not found

**DirectX Errors:**
- D3DCompiler_47.dll is missing
- D3D11.dll error
- XINPUT1_3.dll not found

**Application Errors:**
- 0xc000007b - The application was unable to start correctly
- 0xc0000142 - Application initialization failed

Let's fix each one step by step.`
      },
      {
        heading: 'Fix 1: Install Visual C++ Redistributables',
        content: `Most GTA V DLL errors are caused by missing Visual C++ Runtime.

**Step 1:** Download both versions:
- [VC++ 2015-2022 x64](https://aka.ms/vs/17/release/vc_redist.x64.exe)
- [VC++ 2015-2022 x86](https://aka.ms/vs/17/release/vc_redist.x86.exe)

**Step 2:** Install x64 version first, then x86

**Step 3:** Restart your computer

**Step 4:** Try launching GTA V

This fixes VCRUNTIME140.dll, MSVCP140.dll, and most other Visual C++ errors.`
      },
      {
        heading: 'Fix 2: Install DirectX End-User Runtime',
        content: `For D3DCompiler and XINPUT errors:

**Step 1:** Download [DirectX End-User Runtime](https://www.microsoft.com/en-us/download/details.aspx?id=35)

**Step 2:** Run the installer and complete installation

**Step 3:** Restart your computer

This installs legacy DirectX files needed by GTA V including D3DCompiler_47.dll and XINPUT1_3.dll.`
      },
      {
        heading: 'Fix 3: Verify Game Files',
        content: `If DLL errors persist after installing runtimes:

**Steam:**
1. Open Steam Library
2. Right-click "Grand Theft Auto V"
3. Properties → Installed Files → Verify integrity

**Rockstar Games Launcher:**
1. Open Rockstar Games Launcher
2. Settings → GTA V → Verify Integrity

**Epic Games:**
1. Open Epic Games Launcher
2. Click three dots on GTA V
3. Select "Verify"

This re-downloads any corrupted game files.`
      },
      {
        heading: 'Fix 4: Update Graphics Drivers',
        content: `Outdated GPU drivers can cause D3D11.dll and graphics-related crashes:

**NVIDIA:**
1. Open GeForce Experience
2. Drivers → Check for updates
3. Install latest driver

**AMD:**
1. Open AMD Software
2. Check for updates
3. Install latest driver

**Intel:**
1. Download Intel Driver & Support Assistant
2. Install recommended graphics driver

After updating, restart your computer.`
      },
      {
        heading: 'Fix 5: 0xc000007b Error Specific Fix',
        content: `If you get 0xc000007b error in GTA V:

**Step 1:** Uninstall ALL Visual C++ Redistributables from Control Panel

**Step 2:** Reinstall Visual C++ 2015-2022 (both x64 and x86)

**Step 3:** Also install older versions:
- Visual C++ 2013
- Visual C++ 2012
- Visual C++ 2010

**Step 4:** Run DirectX End-User Runtime installer

**Step 5:** Restart and try GTA V again

This error often means a 32-bit/64-bit mismatch that clean reinstallation fixes.`
      }
    ],
    relatedDlls: ['vcruntime140.dll', 'msvcp140.dll', 'd3dcompiler_47.dll', 'xinput1_3.dll'],
    keywords: ['gta v dll error', 'gta 5 vcruntime140', 'gta v msvcp140', 'gta 5 0xc000007b', 'gta v won\'t start']
  },
  {
    id: 'fix-fortnite-dll-errors',
    slug: 'fortnite-dll-errors-fix',
    title: 'How to Fix DLL Errors in Fortnite',
    metaTitle: 'Fix Fortnite DLL Errors - VCRUNTIME, DirectX, EasyAntiCheat (2025)',
    metaDescription: 'Complete guide to fix all DLL errors when launching Fortnite. Solutions for VCRUNTIME140.dll, D3D errors, and EasyAntiCheat issues.',
    excerpt: 'Fortnite crashing with DLL errors? Learn how to fix Visual C++, DirectX, and anti-cheat related DLL problems.',
    category: 'Gaming',
    publishDate: '2025-03-02',
    updateDate: new Date().toISOString().split('T')[0],
    author: 'Gaming Support Team',
    sections: [
      {
        heading: 'Common Fortnite DLL Errors',
        content: `Fortnite players may encounter these DLL errors:

**Runtime Errors:**
- VCRUNTIME140.dll is missing
- MSVCP140.dll not found
- api-ms-win-crt-runtime-l1-1-0.dll missing

**Graphics Errors:**
- D3D11.dll error
- DXGI.dll error
- vulkan-1.dll not found (when using DirectX 12)

**Anti-Cheat Errors:**
- EasyAntiCheat DLL errors
- BEService DLL problems`
      },
      {
        heading: 'Solution 1: Verify Fortnite Files',
        content: `Start with the simplest fix:

**Step 1:** Open Epic Games Launcher

**Step 2:** Go to Library

**Step 3:** Click the three dots (...) under Fortnite

**Step 4:** Select "Verify"

**Step 5:** Wait for verification to complete (may take 10-20 minutes)

This will redownload any missing or corrupted files including DLLs.`
      },
      {
        heading: 'Solution 2: Install Visual C++ Redistributables',
        content: `For VCRUNTIME and MSVCP errors:

**Download and install:**
- [Visual C++ 2015-2022 x64](https://aka.ms/vs/17/release/vc_redist.x64.exe)
- [Visual C++ 2015-2022 x86](https://aka.ms/vs/17/release/vc_redist.x86.exe)

**Installation Steps:**
1. Close Epic Games Launcher
2. Install x64 version
3. Install x86 version
4. Restart computer
5. Launch Fortnite`
      },
      {
        heading: 'Solution 3: Update Windows',
        content: `For api-ms-win-crt errors:

**Step 1:** Open Windows Settings

**Step 2:** Go to Windows Update

**Step 3:** Check for updates

**Step 4:** Install all available updates

**Step 5:** Restart computer

The Universal C Runtime (UCRT) is included in Windows updates.`
      },
      {
        heading: 'Solution 4: Repair EasyAntiCheat',
        content: `For anti-cheat DLL errors:

**Step 1:** Navigate to Fortnite installation folder:
\`\`\`
C:\\Program Files\\Epic Games\\Fortnite\\FortniteGame\\Binaries\\Win64\\EasyAntiCheat
\`\`\`

**Step 2:** Run \`EasyAntiCheat_Setup.exe\`

**Step 3:** Select "Fortnite" from the dropdown

**Step 4:** Click "Repair Service"

**Step 5:** Restart computer and try Fortnite`
      },
      {
        heading: 'Solution 5: Switch Rendering Mode',
        content: `If you get vulkan-1.dll or D3D errors when using DirectX 12:

**Step 1:** Navigate to:
\`\`\`
%localappdata%\\FortniteGame\\Saved\\Config\\WindowsClient
\`\`\`

**Step 2:** Open \`GameUserSettings.ini\`

**Step 3:** Find and change:
\`\`\`
PreferredRHI=DX12
\`\`\`
to:
\`\`\`
PreferredRHI=DX11
\`\`\`

**Step 4:** Save and launch Fortnite

This switches from DirectX 12 to DirectX 11, which has fewer DLL requirements.`
      }
    ],
    relatedDlls: ['vcruntime140.dll', 'msvcp140.dll', 'd3d11.dll'],
    keywords: ['fortnite dll error', 'fortnite vcruntime140', 'fortnite won\'t launch', 'fortnite d3d error', 'fortnite easyanticheat']
  },
  {
    id: 'fix-adobe-dll-errors',
    slug: 'adobe-photoshop-premiere-dll-errors',
    title: 'Fix DLL Errors in Adobe Photoshop, Premiere Pro, and Creative Cloud',
    metaTitle: 'Fix Adobe DLL Errors - Photoshop, Premiere Pro, After Effects (2025)',
    metaDescription: 'Complete guide to fix DLL errors in Adobe Creative Cloud apps. Solutions for VCRUNTIME, MSVCP, and GPU driver errors in Photoshop, Premiere, After Effects.',
    excerpt: 'Adobe apps crashing with DLL errors? Learn how to fix Visual C++ runtime errors in Photoshop, Premiere Pro, and other Creative Cloud applications.',
    category: 'System',
    publishDate: '2025-03-03',
    updateDate: new Date().toISOString().split('T')[0],
    author: 'System Admin Team',
    sections: [
      {
        heading: 'Common Adobe DLL Errors',
        content: `Adobe Creative Cloud applications may show these errors:

**Visual C++ Runtime:**
- VCRUNTIME140.dll is missing
- VCRUNTIME140_1.dll not found
- MSVCP140.dll is missing
- MSVCP140_1.dll not found

**MFC Runtime:**
- MFC140U.dll is missing

**Legacy Applications (CS6 and older):**
- MSVCR120.dll is missing
- MSVCP120.dll not found
- MSVCR100.dll error

**GPU-Related:**
- OpenCL.dll error
- vulkan-1.dll not found
- OpenGL32.dll issues`
      },
      {
        heading: 'Solution 1: Repair Creative Cloud Installation',
        content: `Use Adobe's built-in repair:

**Step 1:** Open Creative Cloud desktop app

**Step 2:** Click your profile icon → Preferences

**Step 3:** Go to Apps tab

**Step 4:** Click "Repair" next to the problematic app

**Alternative - Clean Uninstall:**
1. Download [Adobe Creative Cloud Cleaner Tool](https://helpx.adobe.com/creative-cloud/kb/cc-cleaner-tool-installation-problems.html)
2. Run the cleaner
3. Reinstall the Adobe application`
      },
      {
        heading: 'Solution 2: Install Visual C++ Redistributables',
        content: `Adobe apps require multiple VC++ versions:

**For CC 2019 and later:**
- [VC++ 2015-2022 x64](https://aka.ms/vs/17/release/vc_redist.x64.exe)
- [VC++ 2015-2022 x86](https://aka.ms/vs/17/release/vc_redist.x86.exe)

**For CS6 and CC 2018:**
- [VC++ 2013 x64](https://aka.ms/highdpimfc2013x64enu)
- [VC++ 2013 x86](https://aka.ms/highdpimfc2013x86enu)

**For CS5 and earlier:**
- VC++ 2012
- VC++ 2010

Install all that apply, then restart your computer.`
      },
      {
        heading: 'Solution 3: Update GPU Drivers',
        content: `For OpenCL, OpenGL, and Vulkan errors:

**NVIDIA (Photoshop, Premiere, After Effects):**
1. Download latest Studio Driver from nvidia.com/drivers
2. Select "Studio Driver" for content creation apps
3. Install and restart

**AMD:**
1. Download from amd.com/support
2. Install AMD Software: PRO Edition for creative apps
3. Restart computer

**Intel:**
1. Download Intel Graphics Driver
2. Ensure you have the latest version`
      },
      {
        heading: 'Solution 4: Adobe-Specific Fixes',
        content: `**Photoshop GPU Issues:**
1. Launch Photoshop
2. Edit → Preferences → Performance
3. Uncheck "Use Graphics Processor"
4. Test if it launches without GPU acceleration

**Premiere Pro OpenCL Errors:**
1. File → Project Settings → General
2. Change Renderer from "Mercury Playback Engine GPU Acceleration" to "Software Only"

**After Effects Memory/DLL Errors:**
1. Edit → Preferences → Memory & Performance
2. Reduce RAM allocated to After Effects`
      },
      {
        heading: 'Solution 5: Run System File Checker',
        content: `For persistent system DLL issues:

**Step 1:** Open Command Prompt as Administrator

**Step 2:** Run:
\`\`\`
sfc /scannow
\`\`\`

**Step 3:** If issues found, run:
\`\`\`
DISM /Online /Cleanup-Image /RestoreHealth
\`\`\`

**Step 4:** Run SFC again:
\`\`\`
sfc /scannow
\`\`\`

**Step 5:** Restart and try Adobe apps again`
      }
    ],
    relatedDlls: ['vcruntime140.dll', 'vcruntime140_1.dll', 'msvcp140.dll', 'mfc140u.dll', 'msvcr120.dll'],
    keywords: ['adobe photoshop dll error', 'premiere pro vcruntime140', 'after effects dll missing', 'creative cloud won\'t launch', 'adobe msvcp140']
  },
  {
    id: 'fix-python-dll-errors',
    slug: 'python-dll-errors-fix',
    title: 'Fix DLL Errors When Running Python (VCRUNTIME140, api-ms-win-crt)',
    metaTitle: 'Fix Python DLL Errors - VCRUNTIME140, api-ms-win-crt (2025)',
    metaDescription: 'Complete guide to fix DLL errors when running Python. Solutions for VCRUNTIME140.dll, api-ms-win-crt-runtime, and MSVCP140.dll errors.',
    excerpt: 'Python won\'t start due to DLL errors? Learn how to fix common Visual C++ runtime issues that prevent Python from running.',
    category: 'System',
    publishDate: '2025-03-04',
    updateDate: new Date().toISOString().split('T')[0],
    author: 'System Admin Team',
    sections: [
      {
        heading: 'Common Python DLL Errors',
        content: `When starting Python, you may see:

**Error 1:** \`python.exe - System Error\`
\`\`\`
The code execution cannot proceed because VCRUNTIME140.dll was not found.
Reinstalling the program may fix this problem.
\`\`\`

**Error 2:**
\`\`\`
api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer
\`\`\`

**Error 3:**
\`\`\`
The code execution cannot proceed because MSVCP140.dll was not found.
\`\`\`

These errors occur because Python 3.5+ requires the Microsoft Visual C++ Runtime.`
      },
      {
        heading: 'Solution 1: Install Visual C++ Redistributable',
        content: `Python 3.5 and later require Visual C++ 2015 or later:

**Step 1:** Download both versions:
- [VC++ 2015-2022 x64](https://aka.ms/vs/17/release/vc_redist.x64.exe) (for 64-bit Python)
- [VC++ 2015-2022 x86](https://aka.ms/vs/17/release/vc_redist.x86.exe) (for 32-bit Python)

**Step 2:** Install the version matching your Python architecture
- If you have 64-bit Python → Install x64
- If you have 32-bit Python → Install x86
- If unsure → Install both

**Step 3:** Restart your computer

**Step 4:** Try running Python again`
      },
      {
        heading: 'Solution 2: Install Windows Updates (api-ms-win-crt)',
        content: `The api-ms-win-crt-runtime DLLs are part of Windows:

**Windows 10/11:**
1. Open Settings → Windows Update
2. Check for updates
3. Install all available updates
4. Restart computer

**Windows 7/8.1:**
1. Install KB2999226 (Universal C Runtime):
   - Go to Microsoft Update Catalog
   - Search for KB2999226
   - Download for your Windows version

**After updating Windows:**
Try running Python again. If still failing, reinstall Visual C++ Redistributable.`
      },
      {
        heading: 'Solution 3: Reinstall Python',
        content: `If installing VC++ doesn't help, reinstall Python:

**Step 1:** Uninstall current Python:
- Control Panel → Programs → Uninstall Python

**Step 2:** Download fresh installer:
- Go to [python.org/downloads](https://python.org/downloads)
- Download the latest version

**Step 3:** Install with these options:
- Check "Add Python to PATH"
- Select "Customize installation"
- Check "Install for all users"

**Step 4:** The Python installer should install required VC++ components automatically`
      },
      {
        heading: 'Solution 4: Use Python from Microsoft Store',
        content: `Alternative installation method that handles dependencies:

**Step 1:** Open Microsoft Store

**Step 2:** Search for "Python"

**Step 3:** Select "Python 3.x" published by Python Software Foundation

**Step 4:** Click "Get" to install

The Microsoft Store version automatically includes all required dependencies.

**Note:** Some advanced use cases may require the python.org version instead.`
      },
      {
        heading: 'Solution 5: Portable/Embedded Python',
        content: `If you can't install VC++ on the system:

**Option 1: Portable Python**
Download WinPython or Python Portable, which bundles VC++ runtime

**Option 2: Embedded Python**
Download the embeddable package from python.org:
1. Go to python.org/downloads/windows
2. Download "Windows embeddable package"
3. Extract to a folder
4. Includes minimal dependencies

**Note:** The embedded version doesn't include pip by default.`
      }
    ],
    relatedDlls: ['vcruntime140.dll', 'msvcp140.dll', 'api-ms-win-crt-runtime-l1-1-0.dll', 'python3.dll'],
    keywords: ['python vcruntime140', 'python dll error', 'python api-ms-win-crt', 'python won\'t start', 'python msvcp140']
  },
  {
    id: 'fix-discord-dll-errors',
    slug: 'discord-dll-errors-fix',
    title: 'Fix Discord DLL Errors and Startup Issues',
    metaTitle: 'Fix Discord DLL Errors - Won\'t Open, VCRUNTIME140, Update Failed (2025)',
    metaDescription: 'Complete guide to fix Discord DLL errors. Solutions for VCRUNTIME140.dll, installation failed, and Discord won\'t open issues.',
    excerpt: 'Discord not opening or showing DLL errors? Learn how to fix Visual C++ runtime errors and other issues preventing Discord from starting.',
    category: 'System',
    publishDate: '2025-03-05',
    updateDate: new Date().toISOString().split('T')[0],
    author: 'System Admin Team',
    sections: [
      {
        heading: 'Common Discord Errors',
        content: `Discord users often see these errors:

**DLL Errors:**
- VCRUNTIME140.dll is missing
- VCRUNTIME140_1.dll not found
- MSVCP140.dll error
- api-ms-win-crt errors

**Other Errors:**
- "Installation has failed"
- Discord opens but shows black/gray screen
- "Update Failed - Retrying"
- Discord crashes on startup`
      },
      {
        heading: 'Solution 1: Install Visual C++ Redistributable',
        content: `Discord requires Visual C++ 2015-2022:

**Step 1:** Close Discord completely (check system tray)

**Step 2:** Download and install:
- [VC++ 2015-2022 x64](https://aka.ms/vs/17/release/vc_redist.x64.exe)

**Step 3:** Restart your computer

**Step 4:** Launch Discord

This fixes most VCRUNTIME and MSVCP errors.`
      },
      {
        heading: 'Solution 2: Clear Discord Cache',
        content: `Corrupted cache can cause DLL loading issues:

**Step 1:** Close Discord completely

**Step 2:** Press \`Win + R\`, type \`%appdata%\`, press Enter

**Step 3:** Delete the "Discord" folder

**Step 4:** Press \`Win + R\`, type \`%localappdata%\`, press Enter

**Step 5:** Delete the "Discord" folder

**Step 6:** Restart computer and reinstall Discord`
      },
      {
        heading: 'Solution 3: Reinstall Discord',
        content: `For persistent issues, clean reinstall:

**Step 1:** Uninstall Discord from Control Panel

**Step 2:** Delete remaining folders:
- \`%appdata%\\Discord\`
- \`%localappdata%\\Discord\`

**Step 3:** Download fresh installer from [discord.com](https://discord.com/download)

**Step 4:** Run installer as Administrator:
- Right-click → Run as administrator`
      },
      {
        heading: 'Solution 4: Update Windows',
        content: `For api-ms-win-crt errors:

**Step 1:** Open Windows Settings

**Step 2:** Go to Windows Update

**Step 3:** Install all updates

**Step 4:** Restart computer

The Universal C Runtime is included in Windows updates.`
      },
      {
        heading: 'Solution 5: Use Discord Web or PTB',
        content: `Temporary alternatives while troubleshooting:

**Discord Web:**
Go to [discord.com/app](https://discord.com/app) in your browser

**Discord PTB (Public Test Build):**
1. Download from [discord.com/download](https://discord.com/download)
2. Scroll down to find "Download Public Test Build"
3. PTB is a separate installation that might work when stable doesn't

**Discord Canary:**
Most experimental version, available from the same download page`
      }
    ],
    relatedDlls: ['vcruntime140.dll', 'vcruntime140_1.dll', 'msvcp140.dll'],
    keywords: ['discord dll error', 'discord vcruntime140', 'discord won\'t open', 'discord installation failed', 'discord update failed']
  },
  {
    id: 'fix-obs-studio-dll-errors',
    slug: 'obs-studio-dll-errors-fix',
    title: 'Fix OBS Studio DLL Errors and Crashes',
    metaTitle: 'Fix OBS Studio DLL Errors - VCRUNTIME, Browser Source, Plugins (2025)',
    metaDescription: 'Complete guide to fix OBS Studio DLL errors. Solutions for VCRUNTIME140.dll, obs-browser plugin, and GPU crashes.',
    excerpt: 'OBS Studio crashing or showing DLL errors? Learn how to fix Visual C++ runtime, browser source, and plugin-related issues.',
    category: 'System',
    publishDate: '2025-03-06',
    updateDate: new Date().toISOString().split('T')[0],
    author: 'System Admin Team',
    sections: [
      {
        heading: 'Common OBS DLL Errors',
        content: `OBS Studio users may encounter:

**Runtime Errors:**
- VCRUNTIME140.dll is missing
- MSVCP140.dll not found

**Plugin Errors:**
- obs-browser.dll failed to load
- obs-websocket.dll error
- Third-party plugin DLL crashes

**GPU-Related:**
- nvEncodeAPI64.dll error (NVIDIA NVENC)
- amf-core.dll error (AMD AMF)
- OpenGL errors`
      },
      {
        heading: 'Solution 1: Install Visual C++ Redistributables',
        content: `OBS requires Visual C++ 2019 or later:

**Step 1:** Download and install:
- [VC++ 2015-2022 x64](https://aka.ms/vs/17/release/vc_redist.x64.exe)

**Step 2:** Restart computer

**Step 3:** Launch OBS

For 32-bit OBS (rare), also install x86 version.`
      },
      {
        heading: 'Solution 2: Update/Reinstall OBS',
        content: `For plugin and browser DLL issues:

**Step 1:** Download latest OBS from [obsproject.com](https://obsproject.com/)

**Step 2:** Choose "Full" installer option

**Step 3:** During installation, ensure "Browser Source" component is selected

**Step 4:** Restart and launch OBS

The browser source plugin requires VC++ runtime - if it fails, the VC++ installation might be corrupted.`
      },
      {
        heading: 'Solution 3: Fix NVENC Errors (NVIDIA)',
        content: `For nvEncodeAPI64.dll and NVIDIA encoder errors:

**Step 1:** Update to latest NVIDIA Game Ready Driver

**Step 2:** In OBS:
1. Go to Settings → Output
2. Change Encoder from "NVIDIA NVENC" to "x264" temporarily

**Step 3:** Test if OBS works with x264

**Step 4:** If NVENC is needed:
- Ensure your GPU supports NVENC (GTX 600 series or newer)
- Try Studio Driver instead of Game Ready Driver`
      },
      {
        heading: 'Solution 4: Reset OBS Configuration',
        content: `For persistent crashes:

**Step 1:** Close OBS

**Step 2:** Navigate to:
\`\`\`
%appdata%\\obs-studio
\`\`\`

**Step 3:** Rename "global.ini" to "global.ini.backup"

**Step 4:** Launch OBS (it will create fresh settings)

**Full Reset:**
Rename the entire "obs-studio" folder to reset completely`
      },
      {
        heading: 'Solution 5: Disable Third-Party Plugins',
        content: `Third-party plugins can cause DLL crashes:

**Step 1:** Navigate to OBS plugins folder:
\`\`\`
C:\\Program Files\\obs-studio\\obs-plugins\\64bit
\`\`\`

**Step 2:** Identify third-party plugins (not obs-*.dll)

**Step 3:** Move them to a backup folder

**Step 4:** Launch OBS

**Step 5:** Re-enable plugins one by one to find the problematic one

**Common problematic plugins:**
- Old StreamFX versions
- Incompatible NDI plugins
- Outdated scene collection managers`
      }
    ],
    relatedDlls: ['vcruntime140.dll', 'msvcp140.dll'],
    keywords: ['obs dll error', 'obs vcruntime140', 'obs browser source', 'obs won\'t start', 'obs nvenc error']
  },
  {
    id: 'fix-unity-dll-errors',
    slug: 'unity-games-dll-errors-fix',
    title: 'Fix DLL Errors in Unity Games (Mono, IL2CPP)',
    metaTitle: 'Fix Unity Game DLL Errors - Mono.dll, GameAssembly.dll (2025)',
    metaDescription: 'Complete guide to fix DLL errors in Unity games. Solutions for Mono.dll, GameAssembly.dll, UnityPlayer.dll, and Visual C++ errors.',
    excerpt: 'Unity games crashing with DLL errors? Learn how to fix common runtime and assembly errors in Unity-based games.',
    category: 'Gaming',
    publishDate: '2025-03-07',
    updateDate: new Date().toISOString().split('T')[0],
    author: 'Gaming Support Team',
    sections: [
      {
        heading: 'Common Unity Game DLL Errors',
        content: `Unity games may show these errors:

**Mono Runtime (Older Unity Games):**
- mono.dll is missing
- mono-2.0-bdwgc.dll not found

**IL2CPP Runtime (Newer Unity Games):**
- GameAssembly.dll error
- UnityPlayer.dll is missing

**Visual C++ Runtime:**
- VCRUNTIME140.dll missing
- MSVCP140.dll not found

**DirectX:**
- D3D11.dll errors
- D3DCompiler errors`
      },
      {
        heading: 'Solution 1: Verify Game Files',
        content: `Unity game DLLs should come with the game:

**Steam:**
1. Right-click game → Properties
2. Local Files → Verify integrity of game files

**Epic Games:**
1. Click three dots on game
2. Verify

**GOG Galaxy:**
1. Click game → Manage
2. Verify / Repair

This restores mono.dll, UnityPlayer.dll, and other game files.`
      },
      {
        heading: 'Solution 2: Install Visual C++ Redistributables',
        content: `Unity games require Visual C++ Runtime:

**Download and install:**
- [VC++ 2015-2022 x64](https://aka.ms/vs/17/release/vc_redist.x64.exe)
- [VC++ 2015-2022 x86](https://aka.ms/vs/17/release/vc_redist.x86.exe)

For older Unity games (pre-2019):
- [VC++ 2013](https://aka.ms/highdpimfc2013x64enu)
- [VC++ 2012](https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe)

Restart computer after installation.`
      },
      {
        heading: 'Solution 3: DirectX Runtime',
        content: `For D3D and DirectX errors:

**Step 1:** Download [DirectX End-User Runtime](https://www.microsoft.com/en-us/download/details.aspx?id=35)

**Step 2:** Run the installer

**Step 3:** Restart computer

**Step 4:** Check game folder for DirectX installer:
\`\`\`
[Game Folder]\\_CommonRedist\\DirectX\\
\`\`\`
Run if present.`
      },
      {
        heading: 'Solution 4: Reinstall Game',
        content: `If DLLs are corrupted beyond repair:

**Step 1:** Note any save game locations (check PCGamingWiki.com)

**Step 2:** Uninstall the game

**Step 3:** Delete remaining game folder

**Step 4:** Reinstall the game

**Step 5:** Before launching:
- Right-click game in library
- Check for runtime installers in game properties
- Run any prerequisite installers`
      },
      {
        heading: 'Solution 5: Unity-Specific Fixes',
        content: `**For GameAssembly.dll errors (IL2CPP games):**
- May be antivirus quarantine - check AV logs
- Add game folder to antivirus exclusions
- Restore quarantined files

**For mono.dll errors:**
- Check game folder for Mono folder
- If missing, verify game files or reinstall

**For modded games:**
- Remove all mods
- Verify game files
- Test vanilla game first
- Re-add mods one at a time

**Common Unity games with DLL issues:**
- Subnautica
- Hollow Knight
- Cuphead
- Risk of Rain 2
- Valheim`
      }
    ],
    relatedDlls: ['vcruntime140.dll', 'msvcp140.dll', 'd3d11.dll'],
    keywords: ['unity game dll error', 'gameassembly.dll', 'unityplayer.dll', 'mono.dll missing', 'unity game won\'t start']
  },
  {
    id: 'fix-windows-11-dll-errors',
    slug: 'windows-11-common-dll-errors',
    title: 'Fix Common DLL Errors After Windows 11 Upgrade',
    metaTitle: 'Fix Windows 11 DLL Errors After Upgrade - Complete Guide (2025)',
    metaDescription: 'Complete guide to fix DLL errors after upgrading to Windows 11. Solutions for app compatibility, Visual C++, and system file issues.',
    excerpt: 'Apps not working after Windows 11 upgrade? Learn how to fix common DLL errors and compatibility issues.',
    category: 'System',
    publishDate: '2025-03-08',
    updateDate: new Date().toISOString().split('T')[0],
    author: 'System Admin Team',
    sections: [
      {
        heading: 'DLL Errors After Windows 11 Upgrade',
        content: `After upgrading to Windows 11, you may see:

**Common Errors:**
- VCRUNTIME140.dll is missing
- MSVCP140.dll not found
- api-ms-win-crt errors
- Old applications won't start
- Games crash on launch

**Causes:**
- Visual C++ Redistributables need reinstallation
- Incompatible applications
- Corrupted upgrade process
- Old drivers`
      },
      {
        heading: 'Solution 1: Reinstall All Visual C++ Redistributables',
        content: `Windows 11 upgrade may corrupt VC++ installations:

**Step 1:** Uninstall all Visual C++ Redistributables:
1. Open Settings → Apps → Installed apps
2. Search "Visual C++"
3. Uninstall each one

**Step 2:** Download and install all versions:

**2015-2022 (Latest):**
- [x64](https://aka.ms/vs/17/release/vc_redist.x64.exe)
- [x86](https://aka.ms/vs/17/release/vc_redist.x86.exe)

**2013:**
- [x64](https://aka.ms/highdpimfc2013x64enu)
- [x86](https://aka.ms/highdpimfc2013x86enu)

**2012:**
- Download from Microsoft

**2010:**
- Download from Microsoft

**Step 3:** Restart computer`
      },
      {
        heading: 'Solution 2: Run Windows Update',
        content: `Windows 11 may need updates for compatibility:

**Step 1:** Open Settings → Windows Update

**Step 2:** Check for updates

**Step 3:** Install all available updates

**Step 4:** Check "Optional updates" for:
- Driver updates
- .NET Framework updates

**Step 5:** Restart computer

Repeat until no more updates are available.`
      },
      {
        heading: 'Solution 3: Repair System Files',
        content: `Upgrade process may have corrupted files:

**Step 1:** Open Terminal as Administrator

**Step 2:** Run DISM first:
\`\`\`
DISM /Online /Cleanup-Image /RestoreHealth
\`\`\`

**Step 3:** Wait for completion (may take 15-30 minutes)

**Step 4:** Run System File Checker:
\`\`\`
sfc /scannow
\`\`\`

**Step 5:** Restart computer`
      },
      {
        heading: 'Solution 4: Reinstall DirectX',
        content: `For games and graphics apps:

**Step 1:** Download [DirectX End-User Runtime](https://www.microsoft.com/en-us/download/details.aspx?id=35)

**Step 2:** Run the installer

**Step 3:** Complete installation

**Step 4:** Restart computer

This installs legacy DirectX 9/10/11 components needed by older games.`
      },
      {
        heading: 'Solution 5: Compatibility Mode for Older Apps',
        content: `If an old application still won't work:

**Step 1:** Right-click the app's .exe file

**Step 2:** Select Properties → Compatibility

**Step 3:** Check "Run this program in compatibility mode for:"

**Step 4:** Select "Windows 10" or "Windows 8"

**Step 5:** Also try:
- Run as administrator
- Disable fullscreen optimizations

**Step 6:** Click Apply and OK

**For persistent issues:**
Search for the app on PCGamingWiki.com for app-specific fixes.`
      }
    ],
    relatedDlls: ['vcruntime140.dll', 'msvcp140.dll', 'ucrtbase.dll', 'api-ms-win-crt-runtime-l1-1-0.dll'],
    keywords: ['windows 11 dll error', 'windows 11 upgrade dll', 'apps not working windows 11', 'vcruntime140 windows 11', 'windows 11 compatibility']
  }
];

// 合并手动和自动生成的指南 + 定时发布指南
const scheduledGuides = (scheduledGuidesData as any).guides || [];
const mergedGuides: Guide[] = [
  ...guidesDatabase,
  ...(autoGeneratedGuides as unknown as Guide[]).filter(
    autoGuide => !guidesDatabase.some(g => g.slug === autoGuide.slug)
  ),
  ...(scheduledGuides as Guide[]).filter(
    scheduledGuide => !guidesDatabase.some(g => g.slug === scheduledGuide.slug) &&
                      !(autoGeneratedGuides as unknown as Guide[]).some(g => g.slug === scheduledGuide.slug)
  )
];

// 获取所有指南
export const getAllGuides = (): Guide[] => {
  return mergedGuides;
};

// 根据 slug 获取指南
export const getGuideBySlug = (slug: string): Guide | undefined => {
  return mergedGuides.find(g => g.slug === slug);
};

// 获取所有 slugs (用于静态生成)
export const getAllGuideSlugs = (): string[] => {
  return mergedGuides.map(g => g.slug);
};

// 根据分类获取指南
export const getGuidesByCategory = (category: Guide['category']): Guide[] => {
  return mergedGuides.filter(g => g.category === category);
};

// 获取相关指南
export const getRelatedGuides = (currentSlug: string, limit: number = 3): Guide[] => {
  const current = getGuideBySlug(currentSlug);
  if (!current) return [];
  
  return mergedGuides
    .filter(g => g.slug !== currentSlug && g.category === current.category)
    .slice(0, limit);
};
